GET http://localhost:3000

###login route

POST http://localhost:3000/auth/register
Content-Type: application/application/json

{
    "email": "test@example.com",
    "password": "test"
}

###register route

POST http://localhost:3000/auth/login

###refresh token route

POST http://localhost:3000/auth/refresh-token

###logout route

DELETE http://localhost:3000/auth/logout

